### PR TITLE
Adapted PSR-2 coding style standard

### PR DESCRIPTION
**Pull request by sadovnik**
Hello!

This pull request adapts this project to [PSR-2](http://www.php-fig.org/psr/psr-2/).

### CODE REVIEW

**Comment by sustmi** [comment]
Thank you for your contribution @sadovnik. Our packages already use coding standards (see https://github.com/shopsys/coding-standards ) that are not fully compatible with PSR-2. Therefore I cannot accept your PR.
We will however add automated coding standards checks (local and using Travis CI) to this repository soon so that it will be easier for other developers to comply with our standards.

**Comment by sadovnik** [comment]
@sustmi could I ask you what's the rationale of having internal coding standards that are conflict with the community's? I feel like the whole point standardizing is loosed. Or not?

**Comment by sustmi** [comment]
Our coding standards were created before we decided to open-source anything. Back then, the only developers who would work with the code were members of our company so it was more sane to create the coding standards so that they will be similar to what we were used to.

Even when the code looks different from what you are used to from some other projects, I still see a point in having *any* coding standards so that the whole code base is consistent.

This repository is only a small part of a bigger project. Before we open source the rest we will consider changing the coding standards in all the projects to be more friendly to the community. Thank you for pointing it out.

**Comment by sustmi** [comment]
Good news! We adapted our coding standards to PSR-2.
Other packages are going to be updated too.

**Pull request merged**
